# Generated by Django 4.1 on 2024-07-09 12:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Residents", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resident",
            name="date",
        ),
        migrations.RemoveField(
            model_name="resident",
            name="numOfPets",
        ),
        migrations.RemoveField(
            model_name="resident",
            name="state",
        ),
    ]
