# Generated by Django 4.1 on 2024-07-09 12:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("Residents", "0002_remove_resident_date_remove_resident_numofpets_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="resident",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="resident",
            name="numOfPets",
            field=models.IntegerField(default=2, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="resident",
            name="state",
            field=models.IntegerField(default=1, max_length=1),
            preserve_default=False,
        ),
    ]
