# Generated by Django 4.1 on 2024-07-10 07:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Images", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Images",
        ),
    ]
