# Generated by Django 4.1 on 2024-07-10 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("Residents", "0003_resident_date_resident_numofpets_resident_state"),
    ]

    operations = [
        migrations.CreateModel(
            name="Incident",
            fields=[
                (
                    "incident_number",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("record_time", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(max_length=20)),
                (
                    "resident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Residents.resident",
                    ),
                ),
            ],
        ),
    ]
