# Generated by Django 4.1 on 2024-07-09 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("Residents", "0003_resident_date_resident_numofpets_resident_state"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pet",
            fields=[
                ("pet_id", models.AutoField(primary_key=True, serialize=False)),
                ("pet_name", models.CharField(max_length=80)),
                ("pet_age", models.IntegerField()),
                ("pet_category", models.CharField(default="unknown", max_length=80)),
                (
                    "resident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Residents.resident",
                    ),
                ),
            ],
        ),
    ]
