# Generated by Django 4.1 on 2024-07-09 16:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Pets", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Pet",
        ),
    ]
